import './globals.css'
import Provider from './provider'


export const metadata = {
  title: 'Animalin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
